import type { FormInputs } from "@/lib/types";

export const SYSTEM_PROMPT = `You are KitPilot. You generate classroom-ready materials grounded STRICTLY in the supplied BeaverBot kit knowledge base. Never invent build steps, slide contents, claims, or materials that are not in that knowledge base. Localize the content to the teacher's grade, class size, lesson duration, session count, cutting method, and special notes. Treat special notes as binding classroom constraints. Never silently ignore a note or claim the standard lesson can run unchanged when a note conflicts with a required kit material. If the knowledge base does not document a requested substitute, say so plainly, distinguish demonstrations from approved build materials, and offer only grounded contingency options. Adapt pacing to those constraints while preserving the four-step maker model: Explore → Plan → Build & Test → Share, followed by Reflect & Iterate. Write for a busy teacher: concrete, scannable, and usable as-is on Monday morning. Return Markdown only, with no code fences or preamble.`;

export function buildInstructions(knowledge: string): string {
  return `${SYSTEM_PROMPT}\n\nAUTHORITATIVE KIT KNOWLEDGE BASE (YAML; single source of truth):\n\n${knowledge}`;
}

function buildTeamPlan(classSize: number): string {
  const teamCount = Math.max(1, Math.ceil(classSize / 4));
  const smaller = Math.floor(classSize / teamCount);
  const largerTeams = classSize % teamCount;
  const smallerTeams = teamCount - largerTeams;
  const parts: string[] = [];

  if (largerTeams > 0) parts.push(`${largerTeams} team${largerTeams === 1 ? "" : "s"} of ${smaller + 1}`);
  if (smallerTeams > 0) parts.push(`${smallerTeams} team${smallerTeams === 1 ? "" : "s"} of ${smaller}`);

  return `${teamCount} total teams (${parts.join(" and ")})`;
}

function constraints(input: FormInputs): string {
  const cutting =
    input.cuttingMethod === "cutter"
      ? "BeaverBot cutting machine"
      : "manual cutting with adult supervision";

  return `- Grade: ${input.grade}\n- Class size: ${input.classSize}\n- Team plan: ${buildTeamPlan(input.classSize)}; use only the knowledge-base roles cutter, drawer, and assembler\n- Lesson length: ${input.lessonLength} minutes per session\n- Number of sessions: ${input.sessions}\n- Total available instructional time: ${input.lessonLength * input.sessions} minutes\n- Cutting method: ${cutting}\n- Special notes: ${input.specialNotes.trim() || "None provided"}`;
}

export function lessonPlanPrompt(input: FormInputs): string {
  return `Create the localized, classroom-ready lesson plan for the Ball Shooter Kit using these teacher constraints:\n\n${constraints(input)}\n\nNON-NEGOTIABLE CONTENT CONTRACT:\n1. Follow the actual lesson arc in this exact order: Quick Game 1: Power Toss! → Quick Game 2: Scoop & Toss! → bridge question → Maker Sheet planning with the named team roles → Build & Test → 3-round Final Challenge → Reflect & Iterate. Do not skip or reorder a phase.\n2. Preserve Explore → Plan → Build & Test → Share, followed by Reflect & Iterate, even when time is tight. Compress activities honestly and flag any setup needed before class.\n3. Include: a concise teacher overview; learning objectives; the proposed NGSS codes from the knowledge base (clearly called proposed alignment); safety notes; before-class prep; and the exact success criteria.\n4. Include a minute-by-minute timeline whose rows add up exactly to ${input.lessonLength * input.sessions} minutes. If there are two sessions, show separate timelines and a clean stopping point.\n5. Include a 15-row slide-by-slide mapping to the included deck, labeled Slide 1 through Slide 15. Map each slide only to a known phase or included asset. Do not invent slide titles, images, wording, or unseen details; when exact content is not present in the knowledge base, say "Use the included slide as provided" and name only the known phase it supports.\n6. Include a materials checklist for ${input.classSize} students and ${buildTeamPlan(input.classSize)}. Use only materials named anywhere in the knowledge base. Include warm-up items (balls and cups) separately from build materials. Where the source does not give a per-team piece count, write "${Math.max(1, Math.ceil(input.classSize / 4))} team sets — exact piece count follows the included templates/assembly instructions" instead of inventing a number.\n7. Use the selected cutting method and repeat the launch-zone rule: never aim at people.\n8. Do not recreate assembly instructions or printable assets; direct the teacher to the included kit assets.\n9. Resolve every special note explicitly. For a no-rubber-bands constraint: state that rubber bands are the only launcher power source documented in the kit and list their classroom quantity as 0; identify the bending plastic spoon only as the documented elastic-force source in Scoop & Toss, not as an approved launcher replacement; do not invent a powered build step; and clearly defer powered testing and the 3-round shooting challenge until an approved replacement and matching assembly guidance exist. Keep the grounded lesson phases in order and use the affected time for non-powered assembly checks, test planning, and reflection without claiming launches occurred.\n\nUse clear H1/H2/H3 headings, checklists, and tables. Return only the finished lesson-plan Markdown.`;
}

export function differentiationPrompt(input: FormInputs, lessonPlan: string): string {
  return `Create the differentiation guide for this exact generated lesson plan and teacher context.\n\nTEACHER CONSTRAINTS:\n${constraints(input)}\n\nGENERATED LESSON PLAN:\n<lesson_plan>\n${lessonPlan}\n</lesson_plan>\n\nNON-NEGOTIABLE CONTENT CONTRACT:\n1. The three tiers are exactly: Guided Builder, Design Engineer, and Innovation Challenge.\n2. The critical design principle is that each tier changes the TASK STRUCTURE, never the reading level and never the student's perceived ability. State this once in teacher-friendly language.\n3. Start with a side-by-side Markdown comparison table covering task structure, planning scaffold, build path, test structure, evidence of success, and teacher moves.\n4. Then provide full, concrete details for each tier grounded only in its knowledge-base definition and the generated timeline. Preserve both Quick Games and the 3-round challenge for every tier.\n5. End with an Adaptations section containing:\n   - an ELL vocabulary card using only lesson-relevant terms, with short student-friendly meanings and useful sentence frames;\n   - fine-motor adaptations that keep the student as the decision-maker and do not remove them from the maker task;\n   - fast-finisher extensions specific to each of the three tiers.\n6. Do not add build materials, build steps, roles, or challenge rules beyond the knowledge base.\n7. Carry every special-note constraint through all three tiers. If powered testing is deferred in the lesson plan, do not reintroduce the prohibited material or claim that any tier completed launches.\n\nUse scannable Markdown. Return only the finished differentiation Markdown.`;
}

export function parentLetterPrompt(input: FormInputs, lessonPlan: string): string {
  return `Write the parent/caregiver letter for the class described below, grounded in the generated lesson plan.\n\nTEACHER CONSTRAINTS:\n${constraints(input)}\n\nGENERATED LESSON PLAN:\n<lesson_plan>\n${lessonPlan}\n</lesson_plan>\n\nNON-NEGOTIABLE CONTENT CONTRACT:\n- Target 180–220 words, with a hard maximum of 250 words total.\n- Warm, welcoming, and free of education jargon.\n- Do not mention standards codes or differentiation tiers.\n- Use exactly this structure and order:\n  1. A short greeting and "What we built"\n  2. "What your child learned" in plain language\n  3. "Ask your child tonight" with exactly 3 conversation starters\n  4. "Try at home" with one safe, 10-minute, no-cost activity using only ordinary items already supported by the knowledge base; include the rule never to aim at people\n- Do not promise outcomes, invent classroom events, or add materials/build steps outside the knowledge base.\n- Reflect the special-note contingency accurately in plain language. Do not tell families that students launched or completed a powered build when testing was deferred.\n\nReturn only the finished letter in Markdown.`;
}
